def mosaic():
    import turtle
    wn = turtle.Screen()
    t = turtle.Turtle()
    t.up()
    t.speed(500)
    t.right(135)
    t.forward(190)
    t.right(-135)
    t.down()
    t.color("black","greenyellow")
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(90)
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(90)
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(90)
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(90)
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(90)
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(90)
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(90)
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(90)
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(90)
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.forward(30)
    t.left(90)
    t.forward(15)
    t.color("black","lawngreen")
    t.left(90)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.forward(30)
    t.right(90)
    t.forward(15)
    t.color("black","green")
    t.right(90)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(90)
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(90)
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(90)
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(90)
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(90)
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(90)
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(90)
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(90)
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(90)
        t.forward(15)
        t.left(90)
    t.end_fill()
    t.forward(30)
    t.left(90)
    t.forward(15)
    t.left(90)
    t.color("black","darkgreen")
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.right(90)
        t.forward(15)
        t.right(90)
    t.end_fill()
    t.forward(30)
    t.right(90)
    t.forward(15)
    t.color("black","purple")
    t.right(90)
    t.begin_fill()
    for i in range(3):
        t.forward(30)
        t.left(120)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(3):
        t.forward(30)
        t.left(120)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(3):
        t.forward(30)
        t.left(120)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(3):
        t.forward(30)
        t.left(120)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(3):
        t.forward(30)
        t.left(120)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(3):
        t.forward(30)
        t.left(120)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(3):
        t.forward(30)
        t.left(120)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(3):
        t.forward(30)
        t.left(120)
    t.end_fill()
    t.forward(30)
    t.begin_fill()
    for i in range(3):
        t.forward(30)
        t.left(120)
    t.end_fill()
    t.forward(30)
    t.left(120)
    t.forward(30)
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(120)
        t.forward(30)
        t.left(60)
    t.end_fill()
    t.left(60)
    t.up()
    t.forward(30)
    t.right(60)
    t.down()
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(120)
        t.forward(30)
        t.left(60)
    t.end_fill()
    t.left(60)
    t.up()
    t.forward(30)
    t.right(60)
    t.down()
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(120)
        t.forward(30)
        t.left(60)
    t.end_fill()
    t.left(60)
    t.up()
    t.forward(30)
    t.right(60)
    t.down()
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(120)
        t.forward(30)
        t.left(60)
    t.end_fill()
    t.left(60)
    t.up()
    t.forward(30)
    t.right(60)
    t.down()
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(120)
        t.forward(30)
        t.left(60)
    t.end_fill()
    t.left(60)
    t.up()
    t.forward(30)
    t.right(60)
    t.down()
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(120)
        t.forward(30)
        t.left(60)
    t.end_fill()
    t.left(60)
    t.up()
    t.forward(30)
    t.right(60)
    t.down()
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(120)
        t.forward(30)
        t.left(60)
    t.end_fill()
    t.left(60)
    t.up()
    t.forward(30)
    t.right(60)
    t.down()
    t.begin_fill()
    for i in range(2):
        t.forward(30)
        t.left(120)
        t.forward(30)
        t.left(60)
    t.end_fill()
    t.left(60)
    t.up()
    t.forward(30)
    t.right(60)
    t.down()
    t.right(60)
    t.forward(30)
    t.right(60)
    t.begin_fill()
    for i in range(3):
        t.forward(30)
        t.right(120)
    t.end_fill()
    t.up()
    t.forward(60)
    t.down()
    t.begin_fill()
    for i in range(3):
        t.forward(30)
        t.right(120)
    t.end_fill()
    t.up()
    t.forward(60)
    t.down()
    t.begin_fill()
    for i in range(3):
        t.forward(30)
        t.right(120)
    t.end_fill()
    t.up()
    t.forward(60)
    t.down()
    t.begin_fill()
    for i in range(3):
        t.forward(30)
        t.right(120)
    t.end_fill()
    t.up()
    t.forward(60)
    t.left(180)
    t.forward(30)
    t.color("black","white")
    t.down()
    t.begin_fill()
    for i in range(3):
        t.forward(30)
        t.right(120)
    t.end_fill()
    t.up()
    t.forward(60)
    t.down()
    t.begin_fill()
    for i in range(3):
        t.forward(30)
        t.right(120)
    t.end_fill()
    t.up()
    t.forward(60)
    t.down()
    t.begin_fill()
    for i in range(3):
        t.forward(30)
        t.right(120)
    t.end_fill()
    t.up()
    t.forward(60)
    t.down()
    t.begin_fill()
    for i in range(3):
        t.forward(30)
        t.right(120)
    t.end_fill()
    t.up()
    t.right(60)
    t.forward(30)
    t.left(60)
    t.down()
    t.color("black","lightskyblue")
    t.begin_fill()
    t.forward(45)
    t.left(90)
    t.forward(80)
    t.left(151)
    t.forward(93)
    t.end_fill()
    t.right(61)
    t.begin_fill()
    for i in range(3):
        t.forward(60)
        t.right(120)
    t.end_fill()
    t.forward(60)
    t.begin_fill()
    for i in range(3):
        t.forward(60)
        t.right(120)
    t.end_fill()
    t.forward(60)
    t.begin_fill()
    for i in range(3):
        t.forward(60)
        t.right(120)
    t.end_fill()
    t.forward(60)
    t.begin_fill()
    t.forward(45)
    t.right(90)
    t.forward(80)
    t.left(210)
    t.forward(90)
    t.end_fill()
    t.right(120)
    t.up()
    t.forward(45)
    t.left(90)
    t.forward(10)
    t.left(90)
    t.down()
    for i in range(27):
        t.begin_fill()
        for z in range(4):
            t.forward(10)
            t.left(90)
        t.end_fill()
        t.forward(10)
    t.right(90)
    t.forward(10)
    t.right(90)
    for i in range(27):
        t.begin_fill()
        for z in range(4):
            t.forward(10)
            t.right(90)
        t.end_fill()
        t.forward(10)
    t.left(90)
    t.forward(10)
    t.left(90)
    for i in range(27):
        t.begin_fill()
        for z in range(4):
            t.forward(10)
            t.left(90)
        t.end_fill()
        t.forward(10)
    t.right(90)
    t.forward(10)
    t.right(90)
    for i in range(27):
        t.begin_fill()
        for z in range(4):
            t.forward(10)
            t.right(90)
        t.end_fill()
        t.forward(10)
    t.color("black","skyblue")
    t.left(90)
    t.forward(10)
    t.left(90)
    for i in range(27):
        t.begin_fill()
        for z in range(4):
            t.forward(10)
            t.left(90)
        t.end_fill()
        t.forward(10)
    t.right(90)
    t.forward(10)
    t.right(90)
    for i in range(27):
        t.begin_fill()
        for z in range(4):
            t.forward(10)
            t.right(90)
        t.end_fill()
        t.forward(10)
    t.left(90)
    t.forward(10)
    t.left(90)
    for i in range(27):
        t.begin_fill()
        for z in range(4):
            t.forward(10)
            t.left(90)
        t.end_fill()
        t.forward(10)
    t.right(90)
    t.forward(10)
    t.right(90)
    for i in range(27):
        t.begin_fill()
        for z in range(4):
            t.forward(10)
            t.right(90)
        t.end_fill()
        t.forward(10)
    t.left(90)
    t.forward(10)
    t.left(90)
    for i in range(27):
        t.begin_fill()
        for z in range(4):
            t.forward(10)
            t.left(90)
        t.end_fill()
        t.forward(10)
    t.right(90)
    t.forward(10)
    t.right(90)
    for i in range(27):
        t.begin_fill()
        for z in range(4):
            t.forward(10)
            t.right(90)
        t.end_fill()
        t.forward(10)
    t.color("black","deepskyblue")
    t.left(90)
    t.forward(10)
    t.left(90)
    for i in range(27):
        t.begin_fill()
        for z in range(4):
            t.forward(10)
            t.left(90)
        t.end_fill()
        t.forward(10)
    t.right(90)
    t.forward(10)
    t.right(90)
    for i in range(27):
        t.begin_fill()
        for z in range(4):
            t.forward(10)
            t.right(90)
        t.end_fill()
        t.forward(10)
    t.left(90)
    t.forward(10)
    t.left(90)
    for i in range(27):
        t.begin_fill()
        for z in range(4):
            t.forward(10)
            t.left(90)
        t.end_fill()
        t.forward(10)
    t.right(90)
    t.forward(10)
    t.right(90)
    for i in range(27):
        t.begin_fill()
        for z in range(4):
            t.forward(10)
            t.right(90)
        t.end_fill()
        t.forward(10)
    # This is to reset the turtle
    t = turtle.Turtle()
    t.speed(500)
    # Starting to make the clouds
    t.color("black","white")
    t.up()
    t.left(90)
    t.forward(105)
    t.right(90)
    t.forward(60)
    t.down()
    t.begin_fill()
    for i in range(6):
        t.left(60)
        t.forward(10)
    t.end_fill()
    t.begin_fill()
    for i in range(6):
        t.right(60)
        t.forward(10)
    t.end_fill()
    t.left(60)
    t.forward(10)
    t.begin_fill()
    for i in range(6):
        t.right(60)
        t.forward(10)
    t.end_fill()
    t.left(180)
    t.forward(10)
    t.left(-60)
    t.forward(10)
    t.right(60)
    t.begin_fill()
    t.forward(10)
    for i in range(6):
        t.left(60)
        t.forward(10)
    t.end_fill()
    t = turtle.Turtle()
    t.speed(500)
    t.color("black","white")
    t.left(90)
    t.up()
    t.forward(76)
    t.left(90)
    t.forward(108)
    t.down()
    t.begin_fill()
    for i in range(6):
        t.left(60)
        t.forward(10)
    t.end_fill()
    t.begin_fill()
    for i in range(6):
        t.right(60)
        t.forward(10)
    t.end_fill()
    t.left(60)
    t.forward(10)
    t.begin_fill()
    for i in range(6):
        t.right(60)
        t.forward(10)
    t.end_fill()
    t.left(180)
    t.forward(10)
    t.left(-60)
    t.forward(10)
    t.right(60)
    t.begin_fill()
    t.forward(10)
    for i in range(6):
        t.left(60)
        t.forward(10)
    t.end_fill()
    t = turtle.Turtle()
    t.speed(500)
    t.color("black","white")
    t.up()
    t.left(90)
    t.forward(39)
    t.right(90)
    t.forward(42)
    t.down()
    t.begin_fill()
    for i in range(6):
        t.left(60)
        t.forward(10)
    t.end_fill()
    t.begin_fill()
    for i in range(6):
        t.right(60)
        t.forward(10)
    t.end_fill()
    t.left(60)
    t.forward(10)
    t.begin_fill()
    for i in range(6):
        t.right(60)
        t.forward(10)
    t.end_fill()
    t.left(180)
    t.forward(10)
    t.left(-60)
    t.forward(10)
    t.right(60)
    t.begin_fill()
    t.forward(10)
    for i in range(6):
        t.left(60)
        t.forward(10)
    t.end_fill()